# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: https://kircute.github.io
date_format: "ordinal"
name: "KirCute's Blog"
title: KirCute's Blog
subtitle: "卡比三卖萌的博客"
description: "KirCute's blog"
keywords: KirCute, blog
favicon: /favicon.ico
encoding: "utf-8"
side_bar_repo_limit: 6

# ---------------- #
#      Author      #
# ---------------- #
author: KirCute_ECT
github_username: KirCute_ECT
github_simpleusername: KirCute
organization: Working Together
email: 951206789@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

  -
    href: /categories/
    label: Archieve

  -
    href: /resume/
    label: Resume

  -
    href: /links/
    label: Links

  -
    href: /projects/
    label: Projects

  -
    href: /about/
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
auto: true
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: KirCute/KirCute.github.io

